initial commit hw 6
tarkravch/nodejs-homework-rest-api pull request #5
Opened 2021-09-15 07:48 UTC by tarkravch

2021-09-15 21:08 UTC, Danil44 requested changes
Потрібно почистити закоментований код

2021-09-16 20:51 UTC, Danil44 commented
Я все ще не отримав відповіді на питання, і в останньому коміті зміни які не відносяться до зауважень

2021-09-17 05:22 UTC, tarkravch commented
Які ще зауваження? Я ж забрав закоментований код!

2021-09-19 13:07 UTC, tarkravch commented
Даніл, добрий день!
То які у вас зауваження, бо я нічого не побачив.

2021-09-21 14:35 UTC, Danil44 requested changes

2021-09-21 14:35 UTC, Danil44 commented on models/user.js
>  const joiSchema = Joi.object({
З назви незрозуміло що це саме за схема

2021-09-21 14:35 UTC, Danil44 commented on controllers/users/signup.js
>    await fs.mkdir(dirPath);
Також незрозуміла назва шляху, що таке dirPath? що за цим шляхом лежить?

2021-09-21 14:35 UTC, Danil44 commented on utils/sendMail.js
> +    return false;
Чому в помилці повертаємо false?

2021-09-21 15:10 UTC, tarkravch commented on models/user.js
>  const joiSchema = Joi.object({
виправив на joiUserSchema

2021-09-21 15:11 UTC, tarkravch commented on controllers/users/signup.js
>    await fs.mkdir(dirPath);
це були параметри методі mkdir(зі шляхом до папки, де зберігаються аватарки). Замінив.

2021-09-21 15:12 UTC, tarkravch commented on utils/sendMail.js
> +    return false;
так казав викладач. Я вставив стандартне throw error.message

2021-09-21 22:02 UTC, Danil44 approved these changes

2021-09-21 22:02 UTC, merged